CREATE TABLE qa_HOSTNAME_THINGY
(ngram STRING, year INT, count BIGINT, volumes BIGINT)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

LOAD DATA INPATH 'qa_HOSTNAME_THINGY/structured'
OVERWRITE INTO TABLE qa_HOSTNAME_THINGY;

SELECT COUNT(*) FROM qa_HOSTNAME_THINGY;

DROP TABLE qa_HOSTNAME_THINGY;
